server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SergiOn/configuration
          search-paths:
            - java/spring-liquibase-okr/authorizationservice
            - java/spring-liquibase-okr/detailservice
            - java/spring-liquibase-okr/eurekaservice
            - java/spring-liquibase-okr/greetingservice
            - java/spring-liquibase-okr/zipkinservice
            - java/spring-liquibase-okr/zuulservice
#          default-label: master
        encrypt:
          enabled: false

logging:
  file: "configservice/logs/configservice.log"
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.springliquibase: DEBUG
