server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SergiOn/configuration
          search-paths:
            - java/spring-liquibase-okr/authorization-service
            - java/spring-liquibase-okr/detail-service
            - java/spring-liquibase-okr/eureka-service
            - java/spring-liquibase-okr/greeting-service
            - java/spring-liquibase-okr/zipkin-service
            - java/spring-liquibase-okr/zuul-service
#          default-label: master
        encrypt:
          enabled: false

logging:
  file: "configservice/logs/configservice.log"
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.springliquibase: DEBUG
