spring:
  application:
    name: authorizationserver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  database:
    driver-class-name: "com.mysql.jdbc.Driver"
  datasource:
    url: "jdbc:mysql://localhost:3306/itemsharingdatabase"
    username: "root"
    password: "root"
    test-while-idle: true
    validation-query: "SELECT 1"

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8901/user

server:
  port: 8901

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

signing:
  key: 345345fsdgsf5345