spring:
#  main:
#    allow-bean-definition-overriding: true
  application:
    name: zuulserver
  zipkin:
    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 0.5

server:
  port: 5555

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  routes:
    userservice: /user/**
    itemservice: /item/**
  ignored-services: '*'
  prefix: /api
  sensitive-headers: Cookie, Set-Cookie


#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.itemsharing: DEBUG
